# -*- coding: utf-8 -*-
"""QUESTION  2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iST6M28wyupBP-8QCK_VS4K2mfhykK20
"""

#*function to get sides of triangle from the user
def Get_sides():
  a=float(input("Enter the side A :"))
  b=float(input("Enter the side B :"))
  c=float(input("Enter the side C :"))
  return a,b,c

#*function to get area of triangle
def find_area(a,b,c):
  import math
  s = (a+b+c)/2
  area = math.sqrt(s*(s-a)*(s-b)*(s-c))
  return area

#*function to get total area
def total_area(area_1,area_2):
  total_area = area_1 + area_2
  print("Total area = ", total_area)
  return total_area

#*function to get % contribution of triangle to area
def contribution(area1,area2):
  total_area=area1+area2
  contribution_of_triangle1 = (100*area1)/total_area
  contribution_of_triangle2 = (100*area2)/total_area
  print("The % contribution of triangle 1 to total area is ",contribution_of_triangle1,"%")
  print("The % contribution of triangle 2 to total area is ",contribution_of_triangle2,"%")
  

print("First Triangle")
a1,b1,c1 = Get_sides()
area_1 = find_area(a1,b1,c1)
print("area of first triangle = ",area_1)


print("Second Triangle")
a2,b2,c2 = Get_sides()
area_2 = find_area(a2,b2,c2)
print("area of second triangle = ",area_2)

total_area(area_1,area_2)
contribution(area_1,area_2)