# -*- coding: utf-8 -*-
"""QUESTION 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sKojHtU8zzaeD60miInX-_-ybVKuu1cz
"""

# **PYTHJON LAB CYCLE 1- QUESTION 1**

   # **1. Develop a program to read a four-digit number and find its**

            # a. Sum of digits
            # b. Reverse
            # c. Difference between the product of digits at the odd position the product of digits at the even position.


# functions to extract the digits from the number :

def ExtractDigits(num):
  
  # extracting the digits into variables digit_1 to digit_4
        
  digit_4=num%10
  num=num//10
  digit_3=num%10
  num=num//10
  digit_2=num%10
  num=num//10
  digit_1=num%10
  return digit_1,digit_2,digit_3,digit_4

  # function to add sum of the digits :
    
def SumOfDigits(digit_1,digit_2,digit_3,digit_4):
  sum = 0
  # sum of digits
  sum = digit_1 + digit_2 + digit_3 + digit_4
  print("sum of digits = " ,sum)

  # function to reverse the number:
    
def ReverseOfNumber(digit_1,digit_2,digit_3,digit_4):
  # reverse of the number
  reverse=(digit_4*1000)+(digit_3*100)+(digit_2*10)+(digit_1)
  print("the reverse of the number = ",reverse)

  #  function to find the diffference between the product of digits in odd position and product of digits in even position

def DiffOfProductOfDigits(digit_1,digit_2,digit_3,digit_4):
  # product of digits in odd position
  product_1=digit_2*digit_4
  # product of digits in even position
  product_2=digit_1*digit_3
  # diffference between the product of digits in odd position and product of digits in even position
  difference = product_2 - product_1
  print("diffference between the product of digits in odd position and product of digits in even position = " ,difference)

 #  functions calling

num=int(input("enter any four digit number : "))    
digit1,digit2,digit3,digit4 = ExtractDigits(num)
SumOfDigits(digit1,digit2,digit3,digit4)
ReverseOfNumber(digit1,digit2,digit3,digit4)
DiffOfProductOfDigits(digit1,digit2,digit3,digit4)