# -*- coding: utf-8 -*-
"""L2Question 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gwQVG7WNEHVMNsQlFO5Dxxl9GNj5hPBR
"""

def rabbit_pairs(n):
  x=0
  y=1
  z=0
  print("months\t\tno of pairs of rabbits")
  for i in range(1,n+1):
    if (i==1):
      print(i,"\t\t",y)
    else:
      z=x+y
      x=y
      y=z
      print(i,"\t\t",z)
n=int(input("enter the number of months: "))
rabbit_pairs(n)